### ISSUE TITLE
touch support not working properly

### ISSUE THREAD

**Issue by sam0x17** [wimpysworld/gpd-pocket2-ubuntu#10]
The touch screen is being recognized as a mouse, instead of as a touch device. As a result two finger scrolling and a number of other things do not seem to work, whereas these do work on Windows. Is there something I'm missing?

**Comment by flexiondotorg** [comment]
From a hardware point of view, the touch screen is working correctly for me. Test on the GPD Pocket and GPD Pocket 2. For example, if I generate a PDF from http://ubuntu-mate.org/blog/ I can open it in Atril (the document viewer) and scroll up/down with 2-fingers and pinch to zoom in/out.

That said, not all applications in Ubuntu MATE are specially adapted for touch support.  So 2-finger scrolling can be interpreted as a draw select.

I am going to close this because in terms of hardware enablement everything is working for correctly and this project is really tracking hardware tweak for the Pocket and Pocket 2 not the general state of touch support in Ubuntu MATE :smiley:
